name: Deploy to cloudtype
on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkcheck
        uses: actions/checkout@v2
      - name: connectconect
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          scope: cloudtype_guide
      - name: BAEPO
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: cloudtype_guide/abcde
          yaml: |-
            name: react
            app: web
            options:
              nodeversion: "14"
              docbase: /build
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
